version: '3.8'

name: anythingllm-light

networks:
  anythingllm-light:
    driver: bridge

services:
  anythingllm:
    container_name: anythingllm-light
    build:
      context: .
      dockerfile: ./docker/Dockerfile
      args:
        ARG_UID: ${UID:-1000}
        ARG_GID: ${GID:-1000}
    cap_add:
      - SYS_ADMIN
    volumes:
      # Configuração de desenvolvimento
      - "./server/.env.development:/app/server/.env"
      # Storage local persistente
      - "./server/storage:/app/server/storage"
      - "./collector/hotdir:/app/collector/hotdir"
      - "./collector/outputs:/app/collector/outputs"
    user: "${UID:-1000}:${GID:-1000}"
    ports:
      - "3001:3001"
    environment:
      - STORAGE_DIR=/app/server/storage
      - NODE_ENV=development
    networks:
      - anythingllm-light
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3001/api/ping"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Opcional: PostgreSQL para testar com banco relacional
  postgres:
    image: postgres:15-alpine
    container_name: anythingllm-postgres-light
    environment:
      POSTGRES_DB: anythingllm
      POSTGRES_USER: anythingllm
      POSTGRES_PASSWORD: dev_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - anythingllm-light
    restart: unless-stopped
    profiles:
      - postgres

volumes:
  postgres_data: